name: Build and Publish image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t jessekercheval/demo-image-test:latest
      - name: push image to docker
        run: |
          docker push jessekercheval/demo-image-test:latest
